version: '3'
services:
  todoback:
    image: todobackend
    ports:
     - 3001:3001
    networks:
      - todolist
    restart: always
  
  todofront:
    depends_on:
      - todoback
    image: todofrontend
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_HOST: todoback
    networks:
      - todolist
    restart: always
  
  todotests:
    depends_on:
      - todoback
      - todofront
    image: todotests
    environment:
      FRONT_HOST: todofront
    networks:
      - todolist

networks:
  todolist: